apiVersion: v1
kind: ServiceAccount
metadata:
 name: ilia
 namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ilia-admin
subjects:
  - kind: ServiceAccount
    # Reference to upper's `metadata.name`
    name: ilia
    # Reference to upper's `metadata.namespace`
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io